server:
  tomcat:
    threads:
      max: 50
      min-spare: 1

smtp:
  server:
    timeout: 1200
fenix:
  print-sql: false
spring:
  datasource:
#    url: jdbc:mysql://mysql:3306/db_readme?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
#    username: root
#    password: 123456
    url: jdbc:h2:file:/var/lib/readme/db_h2
    driver-class-name: org.h2.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: h2
    password: h2

config:
  host: 'http://readme.kischang.top'