server:
  port: 8080
  servlet:
    context-path: /api

fenix:
  print-banner: true
  print-sql: true
  xml-locations: fenix

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/db_readme?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    username: 123
#    password: 123
    url: jdbc:h2:file:./db/h2
    driver-class-name: org.h2.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: h2
    password: h2
  jpa:
    database: H2
    show-sql: false
    hibernate:
      ddl-auto: update

smtp:
  server:
    timeout: 120

config:
  host: 'http://read.kischang.top'
  weixin:
    mp:
      appid: wxcb45330e860cc9ac
      appsecret: 3b1fa6cf90bcd418ffc3a3e34aeef5df
      token: 123
      aesKey: 123
